name: Build & Publish
on:
  push:
    branches:
      - "master"
      - "!dependabot/**"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and publish Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dtc-web:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DATABASE_URL_NON_POOLING=${{ secrets.DATABASE_URL_NON_POOLING }}
          cache-from: type=gha
          cache-to: type=gha,mode=max